def update_age(age, list1, list2, list3, list4, list5, list6, list7, list8, list9, list10, list11):
    if age < 10:
        list1.append(1)
        list2.append(0)
        list3.append(0)
        list4.append(0)
        list5.append(0)
        list6.append(0)
        list7.append(0)
        list8.append(0)
        list9.append(0)
        list10.append(0)
        list11.append(0)
    elif age < 20:
        list1.append(0)
        list2.append(1)
        list3.append(0)
        list4.append(0)
        list5.append(0)
        list6.append(0)
        list7.append(0)
        list8.append(0)
        list9.append(0)
        list10.append(0)
        list11.append(0)
    elif age < 30:
        list1.append(0)
        list2.append(0)
        list3.append(1)
        list4.append(0)
        list5.append(0)
        list6.append(0)
        list7.append(0)
        list8.append(0)
        list9.append(0)
        list10.append(0)
        list11.append(0)
    elif age < 40:
        list1.append(0)
        list2.append(0)
        list3.append(0)
        list4.append(1)
        list5.append(0)
        list6.append(0)
        list7.append(0)
        list8.append(0)
        list9.append(0)
        list10.append(0)
        list11.append(0)
    elif age < 50:
        list1.append(0)
        list2.append(0)
        list3.append(0)
        list4.append(0)
        list5.append(1)
        list6.append(0)
        list7.append(0)
        list8.append(0)
        list9.append(0)
        list10.append(0)
        list11.append(0)
    elif age < 60:
        list1.append(0)
        list2.append(0)
        list3.append(0)
        list4.append(0)
        list5.append(0)
        list6.append(1)
        list7.append(0)
        list8.append(0)
        list9.append(0)
        list10.append(0)
        list11.append(0)
    elif age < 70:
        list1.append(0)
        list2.append(0)
        list3.append(0)
        list4.append(0)
        list5.append(0)
        list6.append(0)
        list7.append(1)
        list8.append(0)
        list9.append(0)
        list10.append(0)
        list11.append(0)
    elif age < 80:
        list1.append(0)
        list2.append(0)
        list3.append(0)
        list4.append(0)
        list5.append(0)
        list6.append(0)
        list7.append(0)
        list8.append(1)
        list9.append(0)
        list10.append(0)
        list11.append(0)
    elif age < 90:
        list1.append(0)
        list2.append(0)
        list3.append(0)
        list4.append(0)
        list5.append(0)
        list6.append(0)
        list7.append(0)
        list8.append(0)
        list9.append(1)
        list10.append(0)
        list11.append(0)
    elif age >= 90:
        list1.append(0)
        list2.append(0)
        list3.append(0)
        list4.append(0)
        list5.append(0)
        list6.append(0)
        list7.append(0)
        list8.append(0)
        list9.append(0)
        list10.append(1)
        list11.append(0)
    else:
        raise


def update_age_undefined(list1, list2, list3, list4, list5, list6, list7, list8, list9, list10, list11):
    list1.append(0)
    list2.append(0)
    list3.append(0)
    list4.append(0)
    list5.append(0)
    list6.append(0)
    list7.append(0)
    list8.append(0)
    list9.append(0)
    list10.append(0)
    list11.append(1)
